image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  default:
    - step:
        name: Checkout repository
        caches:
          - dotnetcore
        script:
          - git checkout $BITBUCKET_BRANCH
          - dotnet restore ColaboratorQ.sln
          - dotnet build ColaboratorQ.sln --no-restore --configuration Release

    - step:
        name: Run Domain Tests
        caches:
          - dotnetcore
        script:
          - dotnet test ./Domain.Tests/Domain.Tests.csproj --configuration Release
        artifacts:
          - test-results/**

    - step:
        name: Run Integration Tests
        services:
          - docker
        caches:
          - dotnetcore
        script:
          - docker info
          - dotnet restore ColaboratorQ.sln
          - dotnet test ./WebApi.IntegrationTests/WebApi.IntegrationTests.csproj --configuration Release
        artifacts:
          - test-results/**

definitions:
  caches:
    dotnetcore: ~/.nuget/packages